// App, Workspace, Session & Agent State Manifest
//
// Generated by scripts/gen-state-manifest.mts — do not edit by hand.
// Regenerate with: pnpm --filter @moonshot-ai/agent-core-v2 gen:state-manifest
//
// Every state key registered into the App-scope IAppStateService, the
// Workspace-scope IWorkspaceStateService, the Session-scope
// ISessionStateService, or the Agent-scope IAgentStateService (see
// src/_base/state/stateRegistry.ts), collected statically from the
// `states.contributeState(...)` call sites and the replayable key chains — a
// `defineState(...).replayable(...)` key is contributed into the Agent-scope
// service by its owner service at construction, and
// carries a `// replayable · durable|transient · undoable? — folds: ...` line.
// Replayable values are excluded from snapshot()/inspect(). A key defined via
// defineState but never registered nor replayable does not appear here. Each entry shows the
// compile-time StateKey<T> value type fully expanded inline, so the manifest is
// self-contained (no imports, no helper declarations). A named type is marked
// at its expansion site with a `/* TypeName — source/file.ts */` comment; a
// `/* TypeName — recursive (...) */ unknown` marker stops a recursive expansion.
// Lib globals (Map/Set/Record/…) are referenced as-is. Generic instantiations
// expand structurally; classes render as their public instance shape. The
// defining source file heads each group.
//
// snapshot() returns JSON-safe deep copies of these values: Maps become plain
// objects (or [key, value] entry arrays when a key is not string/number), Sets
// become arrays, bigints become strings, functions are dropped, circular
// references become '(circular)', and class instances collapse to a '(ClassName)'
// marker — the wire shape of an entry is the JSON projection of the type here.
//
// Index (App: 0 keys · Workspace: 6 keys · Session: 9 keys · Agent: 30 keys)
//   App
//   Workspace
//     workspaceDirs.ephemeralDirs          src/workspace/workspaceDirs/workspaceDirsService.ts
//     workspaceDirs.fileDirs               src/workspace/workspaceDirs/workspaceDirsService.ts
//     workspaceInstructions.current        src/workspace/workspaceInstructions/workspaceInstructionsService.ts
//     workspaceSkillCatalog.contributions  src/features/skill/workspace/workspaceSkillCatalogService.ts
//     workspaceSkillCatalog.merged         src/features/skill/workspace/workspaceSkillCatalogService.ts
//     workspaceTrust.trusted               src/workspace/workspaceTrust/workspaceTrustService.ts
//   Session
//     sessionActivity.current            src/session/sessionActivity/sessionActivityService.ts
//     sessionActivity.folds              src/session/sessionActivity/sessionActivityService.ts
//     sessionLog.rootLevel               src/session/sessionLog/sessionLogService.ts
//     sessionMetadata.data               src/session/sessionMetadata/sessionMetadataService.ts
//     sessionSkillCatalog.contributions  src/features/skill/session/skillCatalogService.ts
//     sessionSkillCatalog.merged         src/features/skill/session/skillCatalogService.ts
//     sessionToolPolicy.state            src/session/sessionToolPolicy/sessionToolPolicyService.ts
//     workspaceContext.additionalDirs    src/session/workspaceContext/workspaceContextService.ts
//     workspaceContext.workDir           src/session/workspaceContext/workspaceContextService.ts
//   Agent
//     agentPlugin.sessionStartRefreshPending  src/agent/plugin/agentPluginService.ts
//     agentsMdReminder.cwd                    src/agent/agentsMdReminder/agentsMdReminderService.ts
//     agentsMdReminder.known                  src/agent/agentsMdReminder/agentsMdReminderService.ts
//     agentsMdReminder.seeded                 src/agent/agentsMdReminder/agentsMdReminderService.ts
//     contextProjector.lastRepairSignature    src/agent/contextProjector/contextProjectorService.ts
//     externalHooks.stopHookContinuationUsed  src/features/externalHooks/agent/agentExternalHooksService.ts
//     interruptionReminder                    src/agent/interruptionReminder/interruptionReminderOps.ts
//     loop.disposing                          src/features/loop/internal/loopLogic.ts
//     loop.lastRequestTraceId                 src/features/loop/internal/loopLogic.ts
//     loop.nextReservedTurnId                 src/features/loop/internal/loopLogic.ts
//     mcp.discovery                           src/agent/mcp/mcpDiscoveryOps.ts
//     mcp.discoveryWritesReady                src/features/toolExecutor/internal/mcpToolProvider.ts
//     mcp.mcpToolsByServer                    src/features/toolExecutor/internal/mcpToolProvider.ts
//     media.registeredKey                     src/agent/media/mediaToolsRegistrar.ts
//     media.resolved                          src/agent/media/mediaResolverService.ts
//     plan                                    src/features/plan/planOps.ts
//     plan.wasActive                          src/features/plan/injection/planModeInjection.ts
//     pluginSessionStartSnapshot              src/agent/plugin/agentPluginOps.ts
//     runtime.binding                         src/agent/runtimeBinding/runtimeBindingService.ts
//     runtimeBinding                          src/agent/runtimeBinding/runtimeBindingOps.ts
//     shellCommand.tasks                      src/agent/shellCommand/shellCommandService.ts
//     staleGuard                              src/features/staleGuard/staleGuardOps.ts
//     stepRetry.failedAttempts                src/features/loop/internal/stepRetry.ts
//     stepRetry.lastFailedDriverId            src/features/loop/internal/stepRetry.ts
//     swarm                                   src/features/swarm/swarmOps.ts
//     task.notificationDelivery               src/features/task/notificationDelivery.ts
//     toolSelect.pendingLoaded                src/features/toolExecutor/internal/selection.ts
//     tower                                   src/features/tower/towerOps.ts
//     tower.owner                             src/features/tower/towerOps.ts
//     userTool                                src/agent/userTool/userToolOps.ts

/** App-scope keys registered into IAppStateService. */
export interface AppStateSnapshot {
}

export type AppStateKey = keyof AppStateSnapshot;

/** Workspace-scope keys registered into IWorkspaceStateService. */
export interface WorkspaceStateSnapshot {
  // src/features/skill/workspace/workspaceSkillCatalogService.ts
  'workspaceSkillCatalog.contributions': Map<string, {
    readonly c: /* SkillContribution — packages/agent-core-v2/src/features/skill/catalog/skillSource.ts */ {
      readonly skills: readonly /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name: string;
        readonly description: string;
        readonly path: string;
        readonly dir: string;
        readonly content: string;
        readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
          readonly name?: string;
          readonly description?: string;
          readonly type?: string;
          readonly whenToUse?: string;
          readonly disableModelInvocation?: boolean;
          readonly isSubSkill?: boolean;
          readonly safe?: boolean;
          readonly arguments?: string | readonly unknown[];
          [key: string]: unknown;
        };
        readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
        readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
          readonly id: string;
          readonly instructions?: string;
        };
        readonly mermaid?: string;
        readonly d2?: string;
        readonly productSpecific?: boolean;
        readonly experimentalFlag?: string;
      }[];
      readonly skipped?: readonly /* SkippedSkill — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly path: string;
        readonly type: string;
        readonly reason: string;
      }[];
      readonly scannedRoots?: readonly string[];
    };
    readonly priority: number;
  }>;
  'workspaceSkillCatalog.merged': /* InMemorySkillCatalog — packages/agent-core-v2/src/features/skill/catalog/registry.ts */ {
    registerBuiltinSkill: (skill: /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    }) => void;
    register: (skill: /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    }, options?: {
      readonly replace?: boolean;
    }) => void;
    recordSkipped: (skills: readonly /* SkippedSkill — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly path: string;
      readonly type: string;
      readonly reason: string;
    }[]) => void;
    addRoots: (roots: readonly string[]) => void;
    getSkill: (name: string) => /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    } | undefined;
    getPluginSkill: (pluginId: string, name: string) => /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    } | undefined;
    renderSkillPrompt: (skill: /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    }, rawArgs: string, context?: {
      readonly sessionId?: string;
    }) => string;
    listSkills: () => readonly /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    }[];
    listInvocableSkills: () => readonly /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    }[];
    getSkillRoots: () => readonly string[];
    getSkippedByPolicy: () => readonly /* SkippedSkill — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly path: string;
      readonly type: string;
      readonly reason: string;
    }[];
    getKimiSkillsDescription: () => string;
    getModelSkillListing: () => string;
  };
  // src/workspace/workspaceDirs/workspaceDirsService.ts
  'workspaceDirs.ephemeralDirs': readonly string[];
  'workspaceDirs.fileDirs': readonly string[];
  // src/workspace/workspaceInstructions/workspaceInstructionsService.ts
  'workspaceInstructions.current': /* WorkspaceInstructionsSnapshot — packages/agent-core-v2/src/workspace/workspaceInstructions/workspaceInstructions.ts */ {
    readonly agentsMd: string | undefined;
    readonly agentsMdWarning: string | undefined;
    readonly agentsMdPaths: readonly string[] | undefined;
  };
  // src/workspace/workspaceTrust/workspaceTrustService.ts
  'workspaceTrust.trusted': boolean;
}

export type WorkspaceStateKey = keyof WorkspaceStateSnapshot;

/** Session-scope keys registered into ISessionStateService. */
export interface SessionStateSnapshot {
  // src/features/skill/session/skillCatalogService.ts
  'sessionSkillCatalog.contributions': Map<string, {
    readonly c: /* SkillContribution — packages/agent-core-v2/src/features/skill/catalog/skillSource.ts */ {
      readonly skills: readonly /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name: string;
        readonly description: string;
        readonly path: string;
        readonly dir: string;
        readonly content: string;
        readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
          readonly name?: string;
          readonly description?: string;
          readonly type?: string;
          readonly whenToUse?: string;
          readonly disableModelInvocation?: boolean;
          readonly isSubSkill?: boolean;
          readonly safe?: boolean;
          readonly arguments?: string | readonly unknown[];
          [key: string]: unknown;
        };
        readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
        readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
          readonly id: string;
          readonly instructions?: string;
        };
        readonly mermaid?: string;
        readonly d2?: string;
        readonly productSpecific?: boolean;
        readonly experimentalFlag?: string;
      }[];
      readonly skipped?: readonly /* SkippedSkill — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly path: string;
        readonly type: string;
        readonly reason: string;
      }[];
      readonly scannedRoots?: readonly string[];
    };
    readonly priority: number;
  }>;
  'sessionSkillCatalog.merged': /* InMemorySkillCatalog — packages/agent-core-v2/src/features/skill/catalog/registry.ts */ {
    registerBuiltinSkill: (skill: /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    }) => void;
    register: (skill: /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    }, options?: {
      readonly replace?: boolean;
    }) => void;
    recordSkipped: (skills: readonly /* SkippedSkill — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly path: string;
      readonly type: string;
      readonly reason: string;
    }[]) => void;
    addRoots: (roots: readonly string[]) => void;
    getSkill: (name: string) => /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    } | undefined;
    getPluginSkill: (pluginId: string, name: string) => /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    } | undefined;
    renderSkillPrompt: (skill: /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    }, rawArgs: string, context?: {
      readonly sessionId?: string;
    }) => string;
    listSkills: () => readonly /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    }[];
    listInvocableSkills: () => readonly /* SkillDefinition — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly name: string;
      readonly description: string;
      readonly path: string;
      readonly dir: string;
      readonly content: string;
      readonly metadata: /* SkillMetadata — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly name?: string;
        readonly description?: string;
        readonly type?: string;
        readonly whenToUse?: string;
        readonly disableModelInvocation?: boolean;
        readonly isSubSkill?: boolean;
        readonly safe?: boolean;
        readonly arguments?: string | readonly unknown[];
        [key: string]: unknown;
      };
      readonly source: /* SkillSource — packages/agent-core-v2/src/features/skill/catalog/types.ts */ 'project' | 'user' | 'extra' | 'builtin';
      readonly plugin?: /* SkillPluginContext — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
        readonly id: string;
        readonly instructions?: string;
      };
      readonly mermaid?: string;
      readonly d2?: string;
      readonly productSpecific?: boolean;
      readonly experimentalFlag?: string;
    }[];
    getSkillRoots: () => readonly string[];
    getSkippedByPolicy: () => readonly /* SkippedSkill — packages/agent-core-v2/src/features/skill/catalog/types.ts */ {
      readonly path: string;
      readonly type: string;
      readonly reason: string;
    }[];
    getKimiSkillsDescription: () => string;
    getModelSkillListing: () => string;
  };
  // src/session/sessionActivity/sessionActivityService.ts
  'sessionActivity.current': /* SessionActivityState — packages/agent-core-v2/src/session/sessionActivity/sessionActivity.ts */ {
    readonly busy: boolean;
    readonly mainTurnActive: boolean;
    readonly pendingInteraction: /* SessionPendingInteraction — packages/agent-core-v2/src/session/sessionActivity/sessionActivity.ts */ 'none' | 'approval' | 'question';
    readonly lastTurnReason?: 'completed' | 'cancelled' | 'failed';
  };
  'sessionActivity.folds': Map<string, /* AgentWorkFold — packages/agent-core-v2/src/session/sessionActivity/sessionActivityService.ts */ {
    turnActive: boolean;
    background: number;
    lastTurnReason?: 'completed' | 'cancelled' | 'failed';
  }>;
  // src/session/sessionLog/sessionLogService.ts
  'sessionLog.rootLevel': /* LogLevelState — packages/agent-core-v2/src/_base/log/logService.ts */ {
    level: /* LogLevel — packages/agent-core-v2/src/_base/log/log.ts */ 'info' | 'off' | 'error' | 'warn' | 'debug';
  };
  // src/session/sessionMetadata/sessionMetadataService.ts
  'sessionMetadata.data': /* SessionMeta — packages/agent-core-v2/src/session/sessionMetadata/sessionMetadata.ts */ {
    readonly id: string;
    readonly version?: number;
    readonly title?: string;
    readonly titleKind?: 'replaceable' | 'generated' | 'custom';
    readonly lastPrompt?: string;
    readonly createdAt: number;
    readonly updatedAt: number;
    readonly archived: boolean;
    readonly archivedAt?: number;
    readonly cwd?: string;
    readonly forkedFrom?: string;
    readonly agents?: Readonly<Record<string, /* AgentMeta — packages/agent-core-v2/src/session/sessionMetadata/sessionMetadata.ts */ {
      readonly homedir?: string;
      readonly type?: 'main' | 'sub' | 'independent';
      readonly parentAgentId?: string | null;
      readonly forkedFrom?: string;
      readonly labels?: Readonly<Record<string, string>>;
      readonly swarmItem?: string;
    }>>;
    readonly custom?: Record<string, unknown>;
    readonly lastTurnReason?: 'completed' | 'cancelled' | 'failed';
  } | undefined;
  // src/session/sessionToolPolicy/sessionToolPolicyService.ts
  'sessionToolPolicy.state': /* SessionToolPolicyState — packages/agent-core-v2/src/session/sessionToolPolicy/sessionToolPolicyService.ts */ {
    readonly disabledTools: readonly string[];
  };
  // src/session/workspaceContext/workspaceContextService.ts
  'workspaceContext.additionalDirs': string[];
  'workspaceContext.workDir': string;
}

export type SessionStateKey = keyof SessionStateSnapshot;

/** Agent-scope keys registered into IAgentStateService. */
export interface AgentStateSnapshot {
  // src/agent/agentsMdReminder/agentsMdReminderService.ts
  'agentsMdReminder.cwd': string | undefined;
  'agentsMdReminder.known': Set<string>;
  'agentsMdReminder.seeded': boolean;
  // src/agent/contextProjector/contextProjectorService.ts
  'contextProjector.lastRepairSignature': string | null;
  // src/agent/interruptionReminder/interruptionReminderOps.ts
  // replayable · durable — folds: InterruptionReminderRecorded
  'interruptionReminder': null;
  // src/agent/mcp/mcpDiscoveryOps.ts
  // replayable · durable — folds: McpToolsDiscovered
  'mcp.discovery': /* McpDiscoveryState — packages/agent-core-v2/src/agent/mcp/mcpDiscoveryOps.ts */ {
    readonly seen: readonly string[];
  };
  // src/agent/media/mediaResolverService.ts
  'media.resolved': Map<string, /* ContentPart — packages/agent-core-v2/src/kosong/contract/message.ts */ /* TextPart — packages/agent-core-v2/src/kosong/contract/message.ts */ {
    type: 'text';
    text: string;
  } | /* ThinkPart — packages/agent-core-v2/src/kosong/contract/message.ts */ {
    type: 'think';
    think: string;
    encrypted?: string;
  } | /* ImageURLPart — packages/agent-core-v2/src/kosong/contract/message.ts */ {
    type: 'image_url';
    imageUrl: {
      url: string;
      id?: string;
    };
  } | /* AudioURLPart — packages/agent-core-v2/src/kosong/contract/message.ts */ {
    type: 'audio_url';
    audioUrl: {
      url: string;
      id?: string;
    };
  } | /* VideoURLPart — packages/agent-core-v2/src/kosong/contract/message.ts */ {
    type: 'video_url';
    videoUrl: {
      url: string;
      id?: string;
    };
  }>;
  // src/agent/media/mediaToolsRegistrar.ts
  'media.registeredKey': string | undefined;
  // src/agent/plugin/agentPluginOps.ts
  // replayable · durable — folds: PluginSessionStartEvent
  'pluginSessionStartSnapshot': /* PluginSessionStartSnapshotState — packages/agent-core-v2/src/agent/plugin/agentPluginOps.ts */ {
    readonly initialized: boolean;
    readonly content?: string;
  };
  // src/agent/plugin/agentPluginService.ts
  'agentPlugin.sessionStartRefreshPending': boolean;
  // src/agent/runtimeBinding/runtimeBindingOps.ts
  // replayable · durable — folds: RuntimeSetBinding
  'runtimeBinding': /* RuntimeBinding — packages/agent-core-v2/src/runtime/runtime.ts */ {
    readonly workspaceId: string;
    readonly runtimeId: string;
  } | undefined;
  // src/agent/runtimeBinding/runtimeBindingService.ts
  'runtime.binding': /* RuntimeBinding — packages/agent-core-v2/src/runtime/runtime.ts */ {
    readonly workspaceId: string;
    readonly runtimeId: string;
  };
  // src/agent/shellCommand/shellCommandService.ts
  'shellCommand.tasks': Map<string, string>;
  // src/agent/userTool/userToolOps.ts
  // replayable · durable — folds: ToolsRegisterUserTool, ToolsUnregisterUserTool
  'userTool': /* UserToolModelState — packages/agent-core-v2/src/agent/userTool/userToolOps.ts */ Map<string, /* UserToolRegistration — packages/agent-core-v2/src/agent/userTool/userTool.ts */ {
    readonly name: string;
    readonly description: string;
    readonly parameters: Record<string, unknown>;
    readonly disclosure?: 'inline' | 'deferred';
  }>;
  // src/features/externalHooks/agent/agentExternalHooksService.ts
  'externalHooks.stopHookContinuationUsed': boolean;
  // src/features/loop/internal/loopLogic.ts
  'loop.disposing': boolean;
  'loop.lastRequestTraceId': string | undefined;
  'loop.nextReservedTurnId': number | undefined;
  // src/features/loop/internal/stepRetry.ts
  'stepRetry.failedAttempts': number;
  'stepRetry.lastFailedDriverId': string | undefined;
  // src/features/plan/injection/planModeInjection.ts
  'plan.wasActive': boolean;
  // src/features/plan/planOps.ts
  // replayable · durable · undoable — folds: PlanModeEnter, PlanModeCancel, PlanModeExit, PlanRevision
  'plan': /* PlanState — packages/agent-core-v2/src/features/plan/planOps.ts */ {
    readonly active: boolean;
    readonly id?: string;
    readonly revisionCount?: Readonly<Record<string, number>>;
  };
  // src/features/staleGuard/staleGuardOps.ts
  // replayable · durable — folds: StaleGuardRecorded, StaleGuardCleared
  'staleGuard': /* StaleGuardModelState — packages/agent-core-v2/src/features/staleGuard/staleGuardOps.ts */ Map<string, number>;
  // src/features/swarm/swarmOps.ts
  // replayable · durable — folds: SwarmModeEnter, SwarmModeExit
  'swarm': 'manual' | 'task' | 'tool' | null;
  // src/features/task/notificationDelivery.ts
  // replayable · durable · undoable — folds: ContextAppendMessage, TaskWaitDelivered
  'task.notificationDelivery': readonly string[];
  // src/features/toolExecutor/internal/mcpToolProvider.ts
  'mcp.discoveryWritesReady': boolean;
  'mcp.mcpToolsByServer': Map<string, string[]>;
  // src/features/toolExecutor/internal/selection.ts
  'toolSelect.pendingLoaded': Set<string>;
  // src/features/tower/towerOps.ts
  // replayable · durable — folds: TowerModeEnter, TowerModeExit
  'tower': boolean;
  // replayable · durable — folds: TowerModeEnter, TowerModeExit
  'tower.owner': string | undefined;
}

export type AgentStateKey = keyof AgentStateSnapshot;
