<!-- Kimi Code app icon for the onboarding wizard, inlined so the mascot's
     eyes hook the shared idle look/blink keyframes in style.css (the same
     .ch-eyes/.ch-eye classes the sidebar logo uses); a click plays one quick
     blink via .blink-now — the sidebar mark's easter egg, minus its
     long-press. The black/white tile swaps by data-color-scheme (two <rect>s,
     no CSS colors); the face gradient id is per-instance so coexisting logos
     (wizard + login card) can't collide. Geometry tracks the KIMI CODE LOGO
     kit's White/Black Background variants; tiles are rounded (rx=27) to match
     the shipped app icon, whose squircle is baked into the artwork so older
     macOS versions (pre-Tahoe, no system masking) still show a rounded icon. -->
<script setup lang="ts">
import { onBeforeUnmount, ref, useId } from 'vue';

withDefaults(defineProps<{ size?: number; variant?: 'system' | 'light' | 'dark' | 'theme' }>(), {
  size: 64,
  variant: 'system',
});

const faceId = `bl-face-${useId()}`;

// Click-to-blink easter egg (same mechanism as the sidebar logo): force a
// reflow so rapid clicks restart the one-shot, then drop the class so the
// idle loop resumes.
const logoRef = ref<SVGSVGElement | null>(null);
let blinkTimer: ReturnType<typeof setTimeout> | undefined;
function blinkOnce(): void {
  const el = logoRef.value;
  if (!el) return;
  el.classList.remove('blink-now');
  void el.getBoundingClientRect();
  el.classList.add('blink-now');
  clearTimeout(blinkTimer);
  blinkTimer = setTimeout(() => el.classList.remove('blink-now'), 300);
}
onBeforeUnmount(() => clearTimeout(blinkTimer));
</script>

<template>
  <!-- brand-mark:start — generated by scripts/build-brand-icons.mjs from
       KIMI CODE LOGO/White Background.svg; do not edit by hand -->
  <svg
    ref="logoRef"
    :class="['brand-logo', `bl-variant-${variant}`]"
    :style="{ width: `${size}px`, height: `${size}px` }"
    viewBox="0 0 120 120"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    role="img"
    aria-label="Kimi Code"
    @click="blinkOnce"
  >
    <rect class="bl-tile bl-tile-light" width="120" height="120" rx="27" fill="black" />
    <rect class="bl-tile bl-tile-dark" width="120" height="120" rx="27" fill="white" />
    <defs>
      <radialGradient :id="faceId" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(55.9622 55.1402) scale(37.9251)">
        <stop stop-color="#117DFB" />
        <stop offset="0.759254" stop-color="#449BFF" />
        <stop offset="1" stop-color="#77B6FF" />
      </radialGradient>
    </defs>
    <path d="M 55.9622 22.2352 C 76.6537 22.2352 93.4274 39.0089 93.4274 59.7004 C 93.4274 80.3918 76.6537 97.1656 55.9622 97.1656 C 35.2708 97.1656 18.4971 80.3918 18.4971 59.7004 C 18.4971 39.0089 35.2708 22.2352 55.9622 22.2352 Z" fill="#2389FF" />
    <path d="M 55.9622 22.2352 C 76.6537 22.2352 93.4274 39.0089 93.4274 59.7004 C 93.4274 80.3918 76.6537 97.1656 55.9622 97.1656 C 35.2708 97.1656 18.4971 80.3918 18.4971 59.7004 C 18.4971 39.0089 35.2708 22.2352 55.9622 22.2352 Z" :fill="`url(#${faceId})`" />
    <g class="ch-eyes" fill="#fff">
      <path class="ch-eye" d="M 51.5123 45.0209 C 51.1532 42.4064 52.9647 39.9981 55.5585 39.6419 C 58.1522 39.2856 60.546 41.1163 60.9051 43.7309 L 61.9986 51.6926 C 62.3576 54.3072 60.5461 56.7154 57.9523 57.0717 C 55.3586 57.4279 52.9648 55.5972 52.6058 52.9827 L 51.5123 45.0209 Z" />
      <path class="ch-eye" d="M 71.2214 42.5099 C 70.8803 40.0261 72.4961 37.7527 74.8305 37.432 C 77.1649 37.1114 79.3338 38.865 79.675 41.3488 L 80.7138 48.9125 C 81.0549 51.3963 79.4391 53.6697 77.1047 53.9904 C 74.7703 54.311 72.6014 52.5573 72.2603 50.0736 L 71.2214 42.5099 Z" />
    </g>
    <rect x="16.9412" y="69.1764" width="85.7647" height="28.0588" rx="3.112" fill="#002E58" />
    <path d="M 24 77.8235 L 31.8773 82.3715 C 32.5257 82.7458 32.5257 83.6816 31.8773 84.0559 L 24 88.6039" stroke="white" stroke-width="3.5294" stroke-linecap="round" />
    <path d="M 40.4116 89.647 H 48.1917" stroke="#007CFF" stroke-width="3.5294" stroke-linecap="round" />
    <path d="M 94.8071 21.2797 C 98.2016 21.2797 100.953 24.0314 100.953 27.4259 C 100.953 30.8204 98.2016 33.5722 94.8071 33.5722 L 89.384 33.5722 C 88.9846 33.5722 88.6609 33.2484 88.6609 32.8491 L 88.6609 27.4259 C 88.6609 24.0314 91.4126 21.2797 94.8071 21.2797 Z" fill="#1783FF" />
  </svg>
  <!-- brand-mark:end -->
</template>

<style scoped>
.brand-logo {
  display: block;
  flex: none;
  cursor: pointer;
  user-select: none;
  touch-action: manipulation;
  /* Lift the tile off near-black dark surfaces (and vice versa). */
  border: 0.5px solid var(--color-line);
  border-radius: 22.5%; /* matches the tile's own rx=27/120 */
  box-sizing: border-box;
}
/* Tile swap by theme — the two <rect>s carry their own fill, so this block
   stays token-clean (same selectors the token layer uses). */
.bl-tile-dark { display: none; }
html[data-color-scheme="dark"] .bl-tile-light { display: none; }
html[data-color-scheme="dark"] .bl-tile-dark { display: block; }
@media (prefers-color-scheme: dark) {
  html[data-color-scheme="system"] .bl-tile-light { display: none; }
  html[data-color-scheme="system"] .bl-tile-dark { display: block; }
}
/* Forced variants (settings app-icon preview) are ICON-accurate: 'light' pins
   the white tile, 'dark' the black one. The tile classes are mode-named
   (bl-tile-light is the BLACK tile shown in light mode for page contrast), so
   this mapping is intentionally the inverse of the theme swap above. */
.brand-logo.bl-variant-light .bl-tile-light { display: none; }
.brand-logo.bl-variant-light .bl-tile-dark { display: block; }
.brand-logo.bl-variant-dark .bl-tile-light { display: block; }
.brand-logo.bl-variant-dark .bl-tile-dark { display: none; }
/* Same-direction appearance for chrome: white tile in light, black in dark. */
.brand-logo.bl-variant-theme .bl-tile-light { display: none; }
.brand-logo.bl-variant-theme .bl-tile-dark { display: block; }
html[data-color-scheme="dark"] .brand-logo.bl-variant-theme .bl-tile-light { display: block; }
html[data-color-scheme="dark"] .brand-logo.bl-variant-theme .bl-tile-dark { display: none; }
@media (prefers-color-scheme: dark) {
  html[data-color-scheme="system"] .brand-logo.bl-variant-theme .bl-tile-light { display: block; }
  html[data-color-scheme="system"] .brand-logo.bl-variant-theme .bl-tile-dark { display: none; }
}
</style>
