import type { SessionSkillRegistry } from '../registry';
import { CHECK_KIMI_CODE_DOCS_SKILL } from './check-kimi-code-docs';
import { CUSTOM_THEME_SKILL } from './custom-theme';
import { IMPORT_FROM_CC_CODEX_SKILL } from './import-from-cc-codex';
import { MCP_CONFIG_SKILL } from './mcp-config';
import {
  SUB_SKILL_CONSOLIDATE,
  SUB_SKILL_PARENT,
  SUB_SKILL_REVIEW,
} from './sub-skill';
import { UPDATE_CONFIG_SKILL } from './update-config';
import { WRITE_GOAL_SKILL } from './write-goal';
import {
  AI_ML_SKILL,
  AI_ML_FINE_TUNING_EXPERT_SKILL,
  AI_ML_MCP_DEVELOPER_SKILL,
  AI_ML_ML_PIPELINE_SKILL,
  AI_ML_PROMPT_ENGINEER_SKILL,
  AI_ML_RAG_ARCHITECT_SKILL,
} from './ai-ml';
import {
  ARCHITECTURE_SKILL,
  ARCHITECTURE_API_DESIGNER_SKILL,
  ARCHITECTURE_ARCHITECTURE_DESIGNER_SKILL,
  ARCHITECTURE_GRAPHQL_ARCHITECT_SKILL,
  ARCHITECTURE_LEGACY_MODERNIZER_SKILL,
  ARCHITECTURE_MICROSERVICES_ARCHITECT_SKILL,
  ARCHITECTURE_SPEC_MINER_SKILL,
} from './architecture';
import {
  BACKEND_FRAMEWORKS_SKILL,
  BACKEND_FRAMEWORKS_CSHARP_DEVELOPER_SKILL,
  BACKEND_FRAMEWORKS_DJANGO_EXPERT_SKILL,
  BACKEND_FRAMEWORKS_DOTNET_CORE_EXPERT_SKILL,
  BACKEND_FRAMEWORKS_FASTAPI_EXPERT_SKILL,
  BACKEND_FRAMEWORKS_JAVA_ARCHITECT_SKILL,
  BACKEND_FRAMEWORKS_LARAVEL_SPECIALIST_SKILL,
  BACKEND_FRAMEWORKS_NESTJS_EXPERT_SKILL,
  BACKEND_FRAMEWORKS_PHP_PRO_SKILL,
  BACKEND_FRAMEWORKS_RAILS_EXPERT_SKILL,
  BACKEND_FRAMEWORKS_SALESFORCE_DEVELOPER_SKILL,
  BACKEND_FRAMEWORKS_SPRING_BOOT_ENGINEER_SKILL,
  BACKEND_FRAMEWORKS_WEBSOCKET_ENGINEER_SKILL,
} from './backend-frameworks';
import {
  DATABASE_SKILL,
  DATABASE_DATA_ANALYST_SKILL,
  DATABASE_DATABASE_OPTIMIZER_SKILL,
  DATABASE_PANDAS_PRO_SKILL,
  DATABASE_POSTGRES_PRO_SKILL,
  DATABASE_SPARK_ENGINEER_SKILL,
  DATABASE_SQL_PRO_SKILL,
} from './database';
import {
  DEBUGGING_SKILL,
  DEBUGGING_DEBUGGER_SKILL,
  DEBUGGING_DEBUGGING_WIZARD_SKILL,
} from './debugging';
import {
  DESIGN_SKILL,
  DESIGN_UX_DESIGNER_SKILL,
  DESIGN_VISUALIZATION_EXPERT_SKILL,
} from './design';
import {
  DEVOPS_INFRA_SKILL,
  DEVOPS_INFRA_CHAOS_ENGINEER_SKILL,
  DEVOPS_INFRA_CLI_DEVELOPER_SKILL,
  DEVOPS_INFRA_CLOUD_ARCHITECT_SKILL,
  DEVOPS_INFRA_DEVOPS_ENGINEER_SKILL,
  DEVOPS_INFRA_KUBERNETES_SPECIALIST_SKILL,
  DEVOPS_INFRA_MONITORING_EXPERT_SKILL,
  DEVOPS_INFRA_SRE_ENGINEER_SKILL,
  DEVOPS_INFRA_TERRAFORM_ENGINEER_SKILL,
} from './devops-infra';
import { EMBEDDED_SYSTEMS_SKILL } from './embedded-systems';
import { FIND_SKILLS_SKILL } from './find-skills';
import {
  FRONTEND_FRAMEWORKS_SKILL,
  FRONTEND_FRAMEWORKS_ANGULAR_ARCHITECT_SKILL,
  FRONTEND_FRAMEWORKS_FLUTTER_EXPERT_SKILL,
  FRONTEND_FRAMEWORKS_FULLSTACK_DEVELOPER_SKILL,
  FRONTEND_FRAMEWORKS_NEXTJS_DEVELOPER_SKILL,
  FRONTEND_FRAMEWORKS_REACT_EXPERT_SKILL,
  FRONTEND_FRAMEWORKS_REACT_NATIVE_EXPERT_SKILL,
  FRONTEND_FRAMEWORKS_SHOPIFY_EXPERT_SKILL,
  FRONTEND_FRAMEWORKS_SWIFT_EXPERT_SKILL,
  FRONTEND_FRAMEWORKS_VUE_EXPERT_SKILL,
  FRONTEND_FRAMEWORKS_VUE_EXPERT_JS_SKILL,
  FRONTEND_FRAMEWORKS_WORDPRESS_PRO_SKILL,
} from './frontend-frameworks';
import { GAME_DEVELOPER_SKILL } from './game-developer';
import {
  LANGUAGES_SKILL,
  LANGUAGES_CPP_PRO_SKILL,
  LANGUAGES_GOLANG_PRO_SKILL,
  LANGUAGES_JAVASCRIPT_PRO_SKILL,
  LANGUAGES_KOTLIN_SPECIALIST_SKILL,
  LANGUAGES_PYTHON_EXPERT_SKILL,
  LANGUAGES_PYTHON_PRO_SKILL,
  LANGUAGES_RUST_ENGINEER_SKILL,
  LANGUAGES_TYPESCRIPT_PRO_SKILL,
} from './languages';
import {
  PROJECT_MANAGEMENT_SKILL,
  PROJECT_MANAGEMENT_ATLASSIAN_MCP_SKILL,
  PROJECT_MANAGEMENT_DECISION_HELPER_SKILL,
  PROJECT_MANAGEMENT_FEATURE_FORGE_SKILL,
  PROJECT_MANAGEMENT_PROJECT_PLANNER_SKILL,
  PROJECT_MANAGEMENT_SPRINT_PLANNER_SKILL,
  PROJECT_MANAGEMENT_STRATEGY_ADVISOR_SKILL,
  PROJECT_MANAGEMENT_THE_FOOL_SKILL,
} from './project-management';
import {
  RESEARCH_WRITING_SKILL,
  RESEARCH_WRITING_ACADEMIC_RESEARCHER_SKILL,
  RESEARCH_WRITING_CODE_DOCUMENTER_SKILL,
  RESEARCH_WRITING_CONTENT_CREATOR_SKILL,
  RESEARCH_WRITING_DEEP_RESEARCH_SKILL,
  RESEARCH_WRITING_EDITOR_SKILL,
  RESEARCH_WRITING_EMAIL_DRAFTER_SKILL,
  RESEARCH_WRITING_FACT_CHECKER_SKILL,
  RESEARCH_WRITING_MEETING_NOTES_SKILL,
  RESEARCH_WRITING_TECHNICAL_WRITER_SKILL,
} from './research-writing';
import {
  SECURITY_SKILL,
  SECURITY_FULLSTACK_GUARDIAN_SKILL,
  SECURITY_SECURE_CODE_GUARDIAN_SKILL,
  SECURITY_SECURITY_REVIEWER_SKILL,
} from './security';
import {
  TESTING_SKILL,
  TESTING_CODE_REVIEWER_SKILL,
  TESTING_PLAYWRIGHT_EXPERT_SKILL,
  TESTING_TEST_MASTER_SKILL,
} from './testing';

export function registerBuiltinSkills(registry: SessionSkillRegistry): void {
  registry.registerBuiltinSkill(MCP_CONFIG_SKILL);
  registry.registerBuiltinSkill(IMPORT_FROM_CC_CODEX_SKILL);
  registry.registerBuiltinSkill(UPDATE_CONFIG_SKILL);
  registry.registerBuiltinSkill(CUSTOM_THEME_SKILL);
  registry.registerBuiltinSkill(WRITE_GOAL_SKILL);
  registry.registerBuiltinSkill(CHECK_KIMI_CODE_DOCS_SKILL);
  registry.registerBuiltinSkill(SUB_SKILL_PARENT);
  registry.registerBuiltinSkill(SUB_SKILL_REVIEW);
  registry.registerBuiltinSkill(SUB_SKILL_CONSOLIDATE);

  // Domain expertise bundles
  registry.registerBuiltinSkill(AI_ML_SKILL);
  registry.registerBuiltinSkill(AI_ML_FINE_TUNING_EXPERT_SKILL);
  registry.registerBuiltinSkill(AI_ML_MCP_DEVELOPER_SKILL);
  registry.registerBuiltinSkill(AI_ML_ML_PIPELINE_SKILL);
  registry.registerBuiltinSkill(AI_ML_PROMPT_ENGINEER_SKILL);
  registry.registerBuiltinSkill(AI_ML_RAG_ARCHITECT_SKILL);
  registry.registerBuiltinSkill(ARCHITECTURE_SKILL);
  registry.registerBuiltinSkill(ARCHITECTURE_API_DESIGNER_SKILL);
  registry.registerBuiltinSkill(ARCHITECTURE_ARCHITECTURE_DESIGNER_SKILL);
  registry.registerBuiltinSkill(ARCHITECTURE_GRAPHQL_ARCHITECT_SKILL);
  registry.registerBuiltinSkill(ARCHITECTURE_LEGACY_MODERNIZER_SKILL);
  registry.registerBuiltinSkill(ARCHITECTURE_MICROSERVICES_ARCHITECT_SKILL);
  registry.registerBuiltinSkill(ARCHITECTURE_SPEC_MINER_SKILL);
  registry.registerBuiltinSkill(BACKEND_FRAMEWORKS_SKILL);
  registry.registerBuiltinSkill(BACKEND_FRAMEWORKS_CSHARP_DEVELOPER_SKILL);
  registry.registerBuiltinSkill(BACKEND_FRAMEWORKS_DJANGO_EXPERT_SKILL);
  registry.registerBuiltinSkill(BACKEND_FRAMEWORKS_DOTNET_CORE_EXPERT_SKILL);
  registry.registerBuiltinSkill(BACKEND_FRAMEWORKS_FASTAPI_EXPERT_SKILL);
  registry.registerBuiltinSkill(BACKEND_FRAMEWORKS_JAVA_ARCHITECT_SKILL);
  registry.registerBuiltinSkill(BACKEND_FRAMEWORKS_LARAVEL_SPECIALIST_SKILL);
  registry.registerBuiltinSkill(BACKEND_FRAMEWORKS_NESTJS_EXPERT_SKILL);
  registry.registerBuiltinSkill(BACKEND_FRAMEWORKS_PHP_PRO_SKILL);
  registry.registerBuiltinSkill(BACKEND_FRAMEWORKS_RAILS_EXPERT_SKILL);
  registry.registerBuiltinSkill(BACKEND_FRAMEWORKS_SALESFORCE_DEVELOPER_SKILL);
  registry.registerBuiltinSkill(BACKEND_FRAMEWORKS_SPRING_BOOT_ENGINEER_SKILL);
  registry.registerBuiltinSkill(BACKEND_FRAMEWORKS_WEBSOCKET_ENGINEER_SKILL);
  registry.registerBuiltinSkill(DATABASE_SKILL);
  registry.registerBuiltinSkill(DATABASE_DATA_ANALYST_SKILL);
  registry.registerBuiltinSkill(DATABASE_DATABASE_OPTIMIZER_SKILL);
  registry.registerBuiltinSkill(DATABASE_PANDAS_PRO_SKILL);
  registry.registerBuiltinSkill(DATABASE_POSTGRES_PRO_SKILL);
  registry.registerBuiltinSkill(DATABASE_SPARK_ENGINEER_SKILL);
  registry.registerBuiltinSkill(DATABASE_SQL_PRO_SKILL);
  registry.registerBuiltinSkill(DEBUGGING_SKILL);
  registry.registerBuiltinSkill(DEBUGGING_DEBUGGER_SKILL);
  registry.registerBuiltinSkill(DEBUGGING_DEBUGGING_WIZARD_SKILL);
  registry.registerBuiltinSkill(DESIGN_SKILL);
  registry.registerBuiltinSkill(DESIGN_UX_DESIGNER_SKILL);
  registry.registerBuiltinSkill(DESIGN_VISUALIZATION_EXPERT_SKILL);
  registry.registerBuiltinSkill(DEVOPS_INFRA_SKILL);
  registry.registerBuiltinSkill(DEVOPS_INFRA_CHAOS_ENGINEER_SKILL);
  registry.registerBuiltinSkill(DEVOPS_INFRA_CLI_DEVELOPER_SKILL);
  registry.registerBuiltinSkill(DEVOPS_INFRA_CLOUD_ARCHITECT_SKILL);
  registry.registerBuiltinSkill(DEVOPS_INFRA_DEVOPS_ENGINEER_SKILL);
  registry.registerBuiltinSkill(DEVOPS_INFRA_KUBERNETES_SPECIALIST_SKILL);
  registry.registerBuiltinSkill(DEVOPS_INFRA_MONITORING_EXPERT_SKILL);
  registry.registerBuiltinSkill(DEVOPS_INFRA_SRE_ENGINEER_SKILL);
  registry.registerBuiltinSkill(DEVOPS_INFRA_TERRAFORM_ENGINEER_SKILL);
  registry.registerBuiltinSkill(EMBEDDED_SYSTEMS_SKILL);
  registry.registerBuiltinSkill(FIND_SKILLS_SKILL);
  registry.registerBuiltinSkill(FRONTEND_FRAMEWORKS_SKILL);
  registry.registerBuiltinSkill(FRONTEND_FRAMEWORKS_ANGULAR_ARCHITECT_SKILL);
  registry.registerBuiltinSkill(FRONTEND_FRAMEWORKS_FLUTTER_EXPERT_SKILL);
  registry.registerBuiltinSkill(FRONTEND_FRAMEWORKS_FULLSTACK_DEVELOPER_SKILL);
  registry.registerBuiltinSkill(FRONTEND_FRAMEWORKS_NEXTJS_DEVELOPER_SKILL);
  registry.registerBuiltinSkill(FRONTEND_FRAMEWORKS_REACT_EXPERT_SKILL);
  registry.registerBuiltinSkill(FRONTEND_FRAMEWORKS_REACT_NATIVE_EXPERT_SKILL);
  registry.registerBuiltinSkill(FRONTEND_FRAMEWORKS_SHOPIFY_EXPERT_SKILL);
  registry.registerBuiltinSkill(FRONTEND_FRAMEWORKS_SWIFT_EXPERT_SKILL);
  registry.registerBuiltinSkill(FRONTEND_FRAMEWORKS_VUE_EXPERT_SKILL);
  registry.registerBuiltinSkill(FRONTEND_FRAMEWORKS_VUE_EXPERT_JS_SKILL);
  registry.registerBuiltinSkill(FRONTEND_FRAMEWORKS_WORDPRESS_PRO_SKILL);
  registry.registerBuiltinSkill(GAME_DEVELOPER_SKILL);
  registry.registerBuiltinSkill(LANGUAGES_SKILL);
  registry.registerBuiltinSkill(LANGUAGES_CPP_PRO_SKILL);
  registry.registerBuiltinSkill(LANGUAGES_GOLANG_PRO_SKILL);
  registry.registerBuiltinSkill(LANGUAGES_JAVASCRIPT_PRO_SKILL);
  registry.registerBuiltinSkill(LANGUAGES_KOTLIN_SPECIALIST_SKILL);
  registry.registerBuiltinSkill(LANGUAGES_PYTHON_EXPERT_SKILL);
  registry.registerBuiltinSkill(LANGUAGES_PYTHON_PRO_SKILL);
  registry.registerBuiltinSkill(LANGUAGES_RUST_ENGINEER_SKILL);
  registry.registerBuiltinSkill(LANGUAGES_TYPESCRIPT_PRO_SKILL);
  registry.registerBuiltinSkill(PROJECT_MANAGEMENT_SKILL);
  registry.registerBuiltinSkill(PROJECT_MANAGEMENT_ATLASSIAN_MCP_SKILL);
  registry.registerBuiltinSkill(PROJECT_MANAGEMENT_DECISION_HELPER_SKILL);
  registry.registerBuiltinSkill(PROJECT_MANAGEMENT_FEATURE_FORGE_SKILL);
  registry.registerBuiltinSkill(PROJECT_MANAGEMENT_PROJECT_PLANNER_SKILL);
  registry.registerBuiltinSkill(PROJECT_MANAGEMENT_SPRINT_PLANNER_SKILL);
  registry.registerBuiltinSkill(PROJECT_MANAGEMENT_STRATEGY_ADVISOR_SKILL);
  registry.registerBuiltinSkill(PROJECT_MANAGEMENT_THE_FOOL_SKILL);
  registry.registerBuiltinSkill(RESEARCH_WRITING_SKILL);
  registry.registerBuiltinSkill(RESEARCH_WRITING_ACADEMIC_RESEARCHER_SKILL);
  registry.registerBuiltinSkill(RESEARCH_WRITING_CODE_DOCUMENTER_SKILL);
  registry.registerBuiltinSkill(RESEARCH_WRITING_CONTENT_CREATOR_SKILL);
  registry.registerBuiltinSkill(RESEARCH_WRITING_DEEP_RESEARCH_SKILL);
  registry.registerBuiltinSkill(RESEARCH_WRITING_EDITOR_SKILL);
  registry.registerBuiltinSkill(RESEARCH_WRITING_EMAIL_DRAFTER_SKILL);
  registry.registerBuiltinSkill(RESEARCH_WRITING_FACT_CHECKER_SKILL);
  registry.registerBuiltinSkill(RESEARCH_WRITING_MEETING_NOTES_SKILL);
  registry.registerBuiltinSkill(RESEARCH_WRITING_TECHNICAL_WRITER_SKILL);
  registry.registerBuiltinSkill(SECURITY_SKILL);
  registry.registerBuiltinSkill(SECURITY_FULLSTACK_GUARDIAN_SKILL);
  registry.registerBuiltinSkill(SECURITY_SECURE_CODE_GUARDIAN_SKILL);
  registry.registerBuiltinSkill(SECURITY_SECURITY_REVIEWER_SKILL);
  registry.registerBuiltinSkill(TESTING_SKILL);
  registry.registerBuiltinSkill(TESTING_CODE_REVIEWER_SKILL);
  registry.registerBuiltinSkill(TESTING_PLAYWRIGHT_EXPERT_SKILL);
  registry.registerBuiltinSkill(TESTING_TEST_MASTER_SKILL);
}

export {
  CHECK_KIMI_CODE_DOCS_SKILL,
  CUSTOM_THEME_SKILL,
  IMPORT_FROM_CC_CODEX_SKILL,
  MCP_CONFIG_SKILL,
  SUB_SKILL_CONSOLIDATE,
  SUB_SKILL_PARENT,
  SUB_SKILL_REVIEW,
  UPDATE_CONFIG_SKILL,
  WRITE_GOAL_SKILL,
  AI_ML_SKILL,
  AI_ML_FINE_TUNING_EXPERT_SKILL,
  AI_ML_MCP_DEVELOPER_SKILL,
  AI_ML_ML_PIPELINE_SKILL,
  AI_ML_PROMPT_ENGINEER_SKILL,
  AI_ML_RAG_ARCHITECT_SKILL,
  ARCHITECTURE_SKILL,
  ARCHITECTURE_API_DESIGNER_SKILL,
  ARCHITECTURE_ARCHITECTURE_DESIGNER_SKILL,
  ARCHITECTURE_GRAPHQL_ARCHITECT_SKILL,
  ARCHITECTURE_LEGACY_MODERNIZER_SKILL,
  ARCHITECTURE_MICROSERVICES_ARCHITECT_SKILL,
  ARCHITECTURE_SPEC_MINER_SKILL,
  BACKEND_FRAMEWORKS_SKILL,
  BACKEND_FRAMEWORKS_CSHARP_DEVELOPER_SKILL,
  BACKEND_FRAMEWORKS_DJANGO_EXPERT_SKILL,
  BACKEND_FRAMEWORKS_DOTNET_CORE_EXPERT_SKILL,
  BACKEND_FRAMEWORKS_FASTAPI_EXPERT_SKILL,
  BACKEND_FRAMEWORKS_JAVA_ARCHITECT_SKILL,
  BACKEND_FRAMEWORKS_LARAVEL_SPECIALIST_SKILL,
  BACKEND_FRAMEWORKS_NESTJS_EXPERT_SKILL,
  BACKEND_FRAMEWORKS_PHP_PRO_SKILL,
  BACKEND_FRAMEWORKS_RAILS_EXPERT_SKILL,
  BACKEND_FRAMEWORKS_SALESFORCE_DEVELOPER_SKILL,
  BACKEND_FRAMEWORKS_SPRING_BOOT_ENGINEER_SKILL,
  BACKEND_FRAMEWORKS_WEBSOCKET_ENGINEER_SKILL,
  DATABASE_SKILL,
  DATABASE_DATA_ANALYST_SKILL,
  DATABASE_DATABASE_OPTIMIZER_SKILL,
  DATABASE_PANDAS_PRO_SKILL,
  DATABASE_POSTGRES_PRO_SKILL,
  DATABASE_SPARK_ENGINEER_SKILL,
  DATABASE_SQL_PRO_SKILL,
  DEBUGGING_SKILL,
  DEBUGGING_DEBUGGER_SKILL,
  DEBUGGING_DEBUGGING_WIZARD_SKILL,
  DESIGN_SKILL,
  DESIGN_UX_DESIGNER_SKILL,
  DESIGN_VISUALIZATION_EXPERT_SKILL,
  DEVOPS_INFRA_SKILL,
  DEVOPS_INFRA_CHAOS_ENGINEER_SKILL,
  DEVOPS_INFRA_CLI_DEVELOPER_SKILL,
  DEVOPS_INFRA_CLOUD_ARCHITECT_SKILL,
  DEVOPS_INFRA_DEVOPS_ENGINEER_SKILL,
  DEVOPS_INFRA_KUBERNETES_SPECIALIST_SKILL,
  DEVOPS_INFRA_MONITORING_EXPERT_SKILL,
  DEVOPS_INFRA_SRE_ENGINEER_SKILL,
  DEVOPS_INFRA_TERRAFORM_ENGINEER_SKILL,
  EMBEDDED_SYSTEMS_SKILL,
  FIND_SKILLS_SKILL,
  FRONTEND_FRAMEWORKS_SKILL,
  FRONTEND_FRAMEWORKS_ANGULAR_ARCHITECT_SKILL,
  FRONTEND_FRAMEWORKS_FLUTTER_EXPERT_SKILL,
  FRONTEND_FRAMEWORKS_FULLSTACK_DEVELOPER_SKILL,
  FRONTEND_FRAMEWORKS_NEXTJS_DEVELOPER_SKILL,
  FRONTEND_FRAMEWORKS_REACT_EXPERT_SKILL,
  FRONTEND_FRAMEWORKS_REACT_NATIVE_EXPERT_SKILL,
  FRONTEND_FRAMEWORKS_SHOPIFY_EXPERT_SKILL,
  FRONTEND_FRAMEWORKS_SWIFT_EXPERT_SKILL,
  FRONTEND_FRAMEWORKS_VUE_EXPERT_SKILL,
  FRONTEND_FRAMEWORKS_VUE_EXPERT_JS_SKILL,
  FRONTEND_FRAMEWORKS_WORDPRESS_PRO_SKILL,
  GAME_DEVELOPER_SKILL,
  LANGUAGES_SKILL,
  LANGUAGES_CPP_PRO_SKILL,
  LANGUAGES_GOLANG_PRO_SKILL,
  LANGUAGES_JAVASCRIPT_PRO_SKILL,
  LANGUAGES_KOTLIN_SPECIALIST_SKILL,
  LANGUAGES_PYTHON_EXPERT_SKILL,
  LANGUAGES_PYTHON_PRO_SKILL,
  LANGUAGES_RUST_ENGINEER_SKILL,
  LANGUAGES_TYPESCRIPT_PRO_SKILL,
  PROJECT_MANAGEMENT_SKILL,
  PROJECT_MANAGEMENT_ATLASSIAN_MCP_SKILL,
  PROJECT_MANAGEMENT_DECISION_HELPER_SKILL,
  PROJECT_MANAGEMENT_FEATURE_FORGE_SKILL,
  PROJECT_MANAGEMENT_PROJECT_PLANNER_SKILL,
  PROJECT_MANAGEMENT_SPRINT_PLANNER_SKILL,
  PROJECT_MANAGEMENT_STRATEGY_ADVISOR_SKILL,
  PROJECT_MANAGEMENT_THE_FOOL_SKILL,
  RESEARCH_WRITING_SKILL,
  RESEARCH_WRITING_ACADEMIC_RESEARCHER_SKILL,
  RESEARCH_WRITING_CODE_DOCUMENTER_SKILL,
  RESEARCH_WRITING_CONTENT_CREATOR_SKILL,
  RESEARCH_WRITING_DEEP_RESEARCH_SKILL,
  RESEARCH_WRITING_EDITOR_SKILL,
  RESEARCH_WRITING_EMAIL_DRAFTER_SKILL,
  RESEARCH_WRITING_FACT_CHECKER_SKILL,
  RESEARCH_WRITING_MEETING_NOTES_SKILL,
  RESEARCH_WRITING_TECHNICAL_WRITER_SKILL,
  SECURITY_SKILL,
  SECURITY_FULLSTACK_GUARDIAN_SKILL,
  SECURITY_SECURE_CODE_GUARDIAN_SKILL,
  SECURITY_SECURITY_REVIEWER_SKILL,
  TESTING_SKILL,
  TESTING_CODE_REVIEWER_SKILL,
  TESTING_PLAYWRIGHT_EXPERT_SKILL,
  TESTING_TEST_MASTER_SKILL,
};
