<!-- apps/web/src/components/onboarding/BrandLogo.vue -->
<!-- Legacy "little blue" brand mark (rounded rect with eye cutouts) for the
     onboarding wizard. WEB FORK — desktop ships the robot mascot generated by
     scripts/build-brand-icons.mjs (its own BrandLogo.vue copy keeps the tile
     and the variant prop); the generator no longer touches this file, so keep
     this divergence on purpose. The eyes are mask cutouts sharing the
     .ch-eyes/.ch-eye idle look/blink keyframes in style.css (same mechanism as
     the sidebar logo); a click plays one quick blink via .blink-now. The mask
     id is per-instance so coexisting logos (wizard + login card) can't
     collide. -->
<script setup lang="ts">
import { onBeforeUnmount, ref, useId } from 'vue';

withDefaults(defineProps<{ size?: number }>(), {
  size: 64,
});

const maskId = `bl-eyes-${useId()}`;

// Click-to-blink easter egg (same mechanism as the sidebar logo): force a
// reflow so rapid clicks restart the one-shot, then drop the class so the
// idle loop resumes.
const logoRef = ref<SVGSVGElement | null>(null);
let blinkTimer: ReturnType<typeof setTimeout> | undefined;
function blinkOnce(): void {
  const el = logoRef.value;
  if (!el) return;
  el.classList.remove('blink-now');
  void el.getBoundingClientRect();
  el.classList.add('blink-now');
  clearTimeout(blinkTimer);
  blinkTimer = setTimeout(() => el.classList.remove('blink-now'), 300);
}
onBeforeUnmount(() => clearTimeout(blinkTimer));
</script>

<template>
  <svg
    ref="logoRef"
    class="brand-logo"
    :style="{ width: `${size}px`, height: `${(size * 22) / 32}px` }"
    viewBox="0 0 32 22"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    role="img"
    aria-label="Kimi Code"
    @click="blinkOnce"
  >
    <defs>
      <mask :id="maskId" maskUnits="userSpaceOnUse">
        <rect x="0" y="0" width="32" height="22" fill="#fff" />
        <g class="ch-eyes" fill="#000">
          <rect class="ch-eye" x="11.8" y="7" width="2.8" height="8" rx="1.4" />
          <rect class="ch-eye" x="17.4" y="7" width="2.8" height="8" rx="1.4" />
        </g>
      </mask>
    </defs>
    <rect x="1" y="1" width="30" height="20" rx="6" fill="var(--logo)" :mask="`url(#${maskId})`" />
  </svg>
</template>

<style scoped>
.brand-logo {
  display: block;
  flex: none;
  cursor: pointer;
  user-select: none;
  touch-action: manipulation;
}
</style>
