#!/usr/bin/env node
/**
 * Fetches models.dev/api.json, strips fields not needed by kimi-code,
 * and writes the result into src/built-in-catalog.ts as a TS constant.
 *
 * Run before release builds so the CLI ships an offline-capable catalog.
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const scriptDir = import.meta.dirname;
const outFile = resolve(scriptDir, "../src/built-in-catalog.ts");
const modelsUrl = process.env.MODELS_DEV_URL || "https://models.dev/api.json";

const KEEP_PROVIDER = new Set(["id", "name", "api", "env", "npm", "type", "models"]);
const KEEP_MODEL = new Set(["id", "name", "limit", "tool_call", "reasoning", "modalities"]);

function stripModel(model) {
  if (typeof model !== "object" || model === null) return undefined;
  const result = {};
  for (const key of Object.keys(model)) {
    if (KEEP_MODEL.has(key)) result[key] = model[key];
  }
  return result;
}

function stripProvider(provider) {
  if (typeof provider !== "object" || provider === null) return undefined;
  const result = {};
  for (const key of Object.keys(provider)) {
    if (!KEEP_PROVIDER.has(key)) continue;
    const value = provider[key];
    if (key === "models") {
      const stripped = {};
      for (const [mId, m] of Object.entries(value)) {
        const s = stripModel(m);
        if (s !== undefined) stripped[mId] = s;
      }
      if (Object.keys(stripped).length > 0) result[key] = stripped;
    } else {
      result[key] = value;
    }
  }
  return result;
}

async function fetchCatalog(url) {
  const res = await fetch(url, { headers: { Accept: "application/json" } });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const raw = await res.json();
  if (typeof raw !== "object" || raw === null || Array.isArray(raw)) {
    throw new Error("invalid payload shape");
  }
  const stripped = {};
  for (const [k, v] of Object.entries(raw)) {
    const p = stripProvider(v);
    if (p !== undefined && Object.keys(p).length > 0) stripped[k] = p;
  }
  return JSON.stringify(stripped);
}

async function main() {
  console.log(`Fetching ${modelsUrl} ...`);
  const json = await fetchCatalog(modelsUrl);
  const content = `// Auto-generated by scripts/update-catalog.mjs. Do not edit manually.
export const BUILT_IN_CATALOG_JSON: string | undefined = ${JSON.stringify(json)};
`;
  writeFileSync(outFile, content, "utf-8");
  console.log(`Wrote ${outFile} (${(json.length / 1024).toFixed(0)} KB JSON)`);
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
