// @moonshot-ai/app-components — product components shared by apps/web and the
// apps/desktop renderer. Source-only package: consumers' bundler transpiles
// these (`exports` points at ./src/*). Support modules (pure helpers,
// composables, assets) live alongside the components and are exported here.

export { default as ErrorBoundary } from './ErrorBoundary.vue';
export { default as FilePreview } from './FilePreview.vue';
export { default as GlobalLoading } from './GlobalLoading.vue';
export { default as HighlightedCode } from './HighlightedCode.vue';
export { default as KimiDoodle } from './KimiDoodle.vue';
export { default as KimiMascot } from './KimiMascot.vue';
export { default as PinnedSessionList } from './PinnedSessionList.vue';
export { default as ResizeHandle } from './ResizeHandle.vue';
export { default as SessionEmojiPicker } from './SessionEmojiPicker.vue';
export { default as SessionRow } from './SessionRow.vue';
export { default as Terminal } from './Terminal.vue';
export { default as WarningToasts } from './WarningToasts.vue';
export { default as WorkspaceGroup } from './WorkspaceGroup.vue';
export { default as FilterSelect } from './admin/FilterSelect.vue';
export { default as MultiSelectMenu } from './admin/MultiSelectMenu.vue';
export { default as SessionAdminMenu } from './admin/SessionAdminMenu.vue';
export { default as SessionAdminPagination } from './admin/SessionAdminPagination.vue';
export { default as SessionAdminTable } from './admin/SessionAdminTable.vue';
export { default as ActivityNotice } from './chat/ActivityNotice.vue';
export { default as ActivityRun } from './chat/ActivityRun.vue';
export { default as AgentDetailPanel } from './chat/AgentDetailPanel.vue';
export { default as AuthMedia } from './chat/AuthMedia.vue';
export { default as ChatPane } from './chat/ChatPane.vue';
export { default as ConversationToc, type ConversationTocItem } from './chat/ConversationToc.vue';
export { default as CronNotice } from './chat/CronNotice.vue';
export { default as DiffView } from './chat/DiffView.vue';
export { default as MediaLightbox } from './chat/MediaLightbox.vue';
export { default as MediaThumb } from './chat/MediaThumb.vue';
export { default as MessageTime } from './chat/MessageTime.vue';
export { default as NotificationCard } from './chat/NotificationCard.vue';
export { default as QuestionCard } from './chat/QuestionCard.vue';
export { default as SelectionActionBubble } from './chat/SelectionActionBubble.vue';
export { default as SideChatPanel } from './chat/SideChatPanel.vue';
export { default as StatusGlyph } from './chat/StatusGlyph.vue';
export { default as StatusPanel } from './chat/StatusPanel.vue';
export { default as ThinkingBlock } from './chat/ThinkingBlock.vue';
export { default as ThinkingPanel } from './chat/ThinkingPanel.vue';
export { default as ToolCall } from './chat/ToolCall.vue';
export { default as TurnDiffPanel } from './chat/TurnDiffPanel.vue';
export { default as TurnFilesSummary } from './chat/TurnFilesSummary.vue';
export { default as TurnFold } from './chat/TurnFold.vue';
export { default as WorkingIndicator } from './chat/WorkingIndicator.vue';
export { default as FilterControl } from './chat/dock/FilterControl.vue';
export { default as GoalPanel } from './chat/dock/GoalPanel.vue';
export { default as PlanPanel } from './chat/dock/PlanPanel.vue';
export { default as SubagentGrid } from './chat/dock/SubagentGrid.vue';
export { default as TasksPane } from './chat/dock/TasksPane.vue';
export { default as TodoCard } from './chat/dock/TodoCard.vue';
export { default as WorkPanelHead } from './chat/dock/WorkPanelHead.vue';
export { default as WorkPill } from './chat/dock/WorkPill.vue';
export { default as AgentTool } from './chat/tool-calls/AgentTool.vue';
export { default as AskUserTool } from './chat/tool-calls/AskUserTool.vue';
export { default as BashTool } from './chat/tool-calls/BashTool.vue';
export { default as EditTool } from './chat/tool-calls/EditTool.vue';
export { default as GenericTool } from './chat/tool-calls/GenericTool.vue';
export { default as GlobTool } from './chat/tool-calls/GlobTool.vue';
export { default as GoalTool } from './chat/tool-calls/GoalTool.vue';
export { default as GrepTool } from './chat/tool-calls/GrepTool.vue';
export { default as MediaTool } from './chat/tool-calls/MediaTool.vue';
export { default as OutputPanel } from './chat/tool-calls/OutputPanel.vue';
export { default as PlanTool } from './chat/tool-calls/PlanTool.vue';
export { default as ReadTool } from './chat/tool-calls/ReadTool.vue';
export { default as SwarmTool } from './chat/tool-calls/SwarmTool.vue';
export { default as TodoTool } from './chat/tool-calls/TodoTool.vue';
export { default as ToolDisclosure } from './chat/tool-calls/ToolDisclosure.vue';
export { default as WaitForTool } from './chat/tool-calls/WaitForTool.vue';
export { default as WebFetchTool } from './chat/tool-calls/WebFetchTool.vue';
export { default as AddWorkspaceDialog } from './dialogs/AddWorkspaceDialog.vue';
export { default as BottomSheet } from './dialogs/BottomSheet.vue';
export { default as ConfirmDialog } from './dialogs/ConfirmDialog.vue';
export { default as ConfirmDialogHost } from './dialogs/ConfirmDialogHost.vue';
export { default as SearchSessionsDialog } from './dialogs/SearchSessionsDialog.vue';
export { default as MobileTopBar } from './mobile/MobileTopBar.vue';
export { default as AddProviderFlow } from './settings/AddProviderFlow.vue';
export { default as ModelPicker } from './settings/ModelPicker.vue';
export { default as PlanUpgradeCard } from './settings/PlanUpgradeCard.vue';
export { default as ProviderForm } from './settings/ProviderForm.vue';
export { default as ProvidersPanel } from './settings/ProvidersPanel.vue';
export { default as SecondaryModelPicker } from './settings/SecondaryModelPicker.vue';

export * from './chatTurnRendering';
export * from './chat/tool-calls/toolArgs';
export * from './chat/tool-calls/askUserToolParse';
export * from './chat/tool-calls/toolRegistry';
export * from './admin/pageItems';
export * from './admin/formatAdminTime';
export * from './admin/adminBatchToast';
export * from './admin/useAnchoredMenu';
export * from './lib/toolMeta';
export * from './lib/activitySummary';
export { useDialogFocus } from './composables/useDialogFocus';
